// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _DATATRAININGS_H_
#define _DATATRAININGS_H_

EXTERN_PATTERN( PAT__ReadDqTraining )
EXTERN_PATTERN( PAT__WriteDqTrainingTxSide )

#endif
