#pragma once

#include "TestProgApp/public.h"
#include "Utilities.h"

namespace dutpin
{
	DECLARE_DUT_PIN( DQS_t	) ;
	DECLARE_DUT_PIN( DQS_c	) ;
	DECLARE_DUT_PIN( DQ0	) ;
	DECLARE_DUT_PIN( DQ1	) ;
	DECLARE_DUT_PIN( DQ2	) ;
	DECLARE_DUT_PIN( DQ3	) ;
	DECLARE_DUT_PIN( DQ4	) ;
	DECLARE_DUT_PIN( DQ5	) ;
	DECLARE_DUT_PIN( DQ6	) ;
	DECLARE_DUT_PIN( DQ7	) ;
	DECLARE_DUT_PIN( CLE	) ;
	DECLARE_DUT_PIN( ALE	) ;
	DECLARE_DUT_PIN( RE_t	) ;
	DECLARE_DUT_PIN( RE_c	) ;
	DECLARE_DUT_PIN( RB0n	) ;
	DECLARE_DUT_PIN( RB1n	) ;
	DECLARE_DUT_PIN( WEn	) ;
	DECLARE_DUT_PIN( CE0n	) ;
	DECLARE_DUT_PIN( CE1n	) ;
	DECLARE_DUT_PIN( WPn	) ;
	DECLARE_DUT_PIN( ENi	) ; 
	DECLARE_DUT_PIN( ENo	) ; 
	DECLARE_DUT_PIN( VSP0	) ; 
	DECLARE_DUT_PIN( VSP1	) ; 
	DECLARE_DUT_PIN( VSP2	) ; 

	DECLARE_DUT_PIN( VCC	) ;
	DECLARE_DUT_PIN( VCCQ	) ;
	DECLARE_DUT_PIN( VPP	) ;
	DECLARE_DUT_PIN( VREFQ	) ;
}