#include "stdafx.h"
#include "DutPins.h"

DEFINE_DUT_PIN( DQS_t	) { }
DEFINE_DUT_PIN( DQS_c	) { }
DEFINE_DUT_PIN( DQ0		) { }
DEFINE_DUT_PIN( DQ1		) { }
DEFINE_DUT_PIN( DQ2		) { }
DEFINE_DUT_PIN( DQ3		) { }
DEFINE_DUT_PIN( DQ4		) { }
DEFINE_DUT_PIN( DQ5		) { }
DEFINE_DUT_PIN( DQ6		) { }
DEFINE_DUT_PIN( DQ7		) { }
DEFINE_DUT_PIN( CLE		) { }
DEFINE_DUT_PIN( ALE		) { }
DEFINE_DUT_PIN( RE_t	) { }
DEFINE_DUT_PIN( RE_c	) { }
DEFINE_DUT_PIN( RB0n	) { }
DEFINE_DUT_PIN( RB1n	) { }
DEFINE_DUT_PIN( WEn		) { }
DEFINE_DUT_PIN( CE0n	) { }
DEFINE_DUT_PIN( CE1n	) { }
DEFINE_DUT_PIN( WPn		) { }
DEFINE_DUT_PIN( ENi		) { }
DEFINE_DUT_PIN( ENo		) { }
DEFINE_DUT_PIN( VSP0	) { }
DEFINE_DUT_PIN( VSP1	) { }
DEFINE_DUT_PIN( VSP2	) { }

DEFINE_DUT_PIN( VCC		) { }
DEFINE_DUT_PIN( VCCQ	) { }
DEFINE_DUT_PIN( VPP		) { }
DEFINE_DUT_PIN( VREFQ	) { }
