// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _DV_PATS_H_
#define _DV_PATS_H_

EXTERN_PATTERN( SUB__FHS )
EXTERN_PATTERN( PAT__FlagHandshake )
EXTERN_PATTERN( PAT__userramaddress )
EXTERN_PATTERN( PAT__FlsShutdown )

#endif
