// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _FEATURES_H_
#define _FEATURES_H_

EXTERN_PATTERN( PAT__SetFeaturesJamRam )
EXTERN_PATTERN( PAT__GetFeaturesJamRam )
EXTERN_PATTERN( PAT__SetFeaturesDmain )
EXTERN_PATTERN( PAT__GetFeaturesDmain )

#endif
