// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _LEVELSETS_H_
#define _LEVELSETS_H_

EXTERN_PATTERN( PAT__PE_LevelSets )
EXTERN_PATTERN( PAT__DPS_LevelSets_set )
EXTERN_PATTERN( PAT__DPS_LevelSets_twk )
EXTERN_PATTERN( PAT__HV_LevelSets_set )
EXTERN_PATTERN( PAT__HV_LevelSets_twk )

#endif
