// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _MULTIPLANEREAD_H_
#define _MULTIPLANEREAD_H_

EXTERN_PATTERN( SUB__ChangeReadColumnEnhanced )
EXTERN_PATTERN( SUB__ChangeReadColumn )
EXTERN_PATTERN( SUB__ReadPageMP )
EXTERN_PATTERN( PAT__ReadOnePage_MultiPlane_SLC )

#endif
