// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _MULTIPLANEPROGRAM_H_
#define _MULTIPLANEPROGRAM_H_

EXTERN_PATTERN( PAT__ProgramOnePage_MultiPlane_SLC )
EXTERN_PATTERN( PAT__ProgramOnePage_MultiPlane_TLC )

#endif
