// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _MULTIPLANEERASE_H_
#define _MULTIPLANEERASE_H_

EXTERN_PATTERN( PAT__EraseOneBlock_MultiPlane )

#endif
