// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _READID_H_
#define _READID_H_

EXTERN_PATTERN( PAT__ReadId90hWithAddress20h )
EXTERN_PATTERN( PAT__ReadId90hWithAddress20h_dmain_x4 )
EXTERN_PATTERN( PAT__ReadId90hWithAddress20h_dmain )

#endif
