// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _READSTATUS_H_
#define _READSTATUS_H_

EXTERN_PATTERN( PAT__ReadStatus_0x70 )
EXTERN_PATTERN( PAT__ReadStatusEnhanced_0x78 )

#endif
