// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _READPARAMETERS_H_
#define _READPARAMETERS_H_

EXTERN_PATTERN( PAT__ReadParameters )
EXTERN_PATTERN( PAT__ReadParameters_x4 )

#endif
