// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _SINGLEPLANEERASE_H_
#define _SINGLEPLANEERASE_H_

EXTERN_PATTERN( SUB__POLL_TBERS )
EXTERN_PATTERN( PAT__EraseOneBlock_SinglePlane )

#endif
