// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _WRITEREADCACHE_H_
#define _WRITEREADCACHE_H_

EXTERN_PATTERN( PAT__WriteReadCache_x4 )
EXTERN_PATTERN( PAT__WriteReadCache )
EXTERN_PATTERN( PAT__ODT_SETUP )
EXTERN_PATTERN( PAT__WriteReadCache_INV )
EXTERN_PATTERN( PAT__WriteReadCache_RND_x4 )
EXTERN_PATTERN( PAT__WriteReadCache_RND )
EXTERN_PATTERN( PAT__HwTraining_RND )
EXTERN_PATTERN( PAT__WriteReadCache_DBI )
EXTERN_PATTERN( PAT__WriteReadCache_DBM )
EXTERN_PATTERN( PAT__WriteReadCache_DBM_x4 )
EXTERN_PATTERN( PAT__WriteReadCache_LFSR )
EXTERN_PATTERN( PAT__WriteCache_RND_x4 )
EXTERN_PATTERN( PAT__WriteCache_x4 )
EXTERN_PATTERN( PAT__ReadCache_RND_x4 )
EXTERN_PATTERN( PAT__WriteCache_RND )
EXTERN_PATTERN( PAT__ReadCache_RND )
EXTERN_PATTERN( PAT__ReadCache_EBM_MASK_x4 )
EXTERN_PATTERN( PAT__WriteReadCache_EBM_x4 )
EXTERN_PATTERN( PAT__WriteReadCache_EBM )
EXTERN_PATTERN( PAT__WriteCache )
EXTERN_PATTERN( PAT__ReadCache_EBM )

#endif
